# Generated by Django 5.2.7 on 2025-11-16 21:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('contraseña', models.CharField(max_length=128)),
                ('calle', models.CharField(blank=True, max_length=200)),
                ('numero_casa', models.CharField(blank=True, max_length=50)),
                ('colonia', models.CharField(blank=True, max_length=100)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=20)),
                ('descripcion_direccion', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('metodo_pago', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hombre',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('talla', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('material', models.CharField(blank=True, max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/hombre/')),
                ('tipo', models.CharField(max_length=100)),
                ('temporada', models.CharField(choices=[('verano', 'Verano'), ('invierno', 'Invierno')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mujer',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('talla', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('material', models.CharField(blank=True, max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/mujer/')),
                ('temporada', models.CharField(choices=[('verano', 'Verano'), ('invierno', 'Invierno')], max_length=20)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ninas',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=100)),
                ('talla', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('descripcion', models.TextField(blank=True)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('temporada', models.CharField(choices=[('verano', 'Verano'), ('invierno', 'Invierno')], max_length=20)),
                ('edad_recomendada', models.CharField(blank=True, max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/ninas/')),
            ],
        ),
        migrations.CreateModel(
            name='Ninos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=100)),
                ('talla', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('descripcion', models.TextField(blank=True)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('temporada', models.CharField(choices=[('verano', 'Verano'), ('invierno', 'Invierno')], max_length=20)),
                ('edad_recomendada', models.CharField(blank=True, max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/ninos/')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=200)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_pedido', models.DateTimeField(default=django.utils.timezone.now)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('direccion', models.TextField(blank=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='app_famfashion.cliente')),
                ('id_producto_hombre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_famfashion.hombre')),
                ('id_producto_mujer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_famfashion.mujer')),
                ('id_producto_ninas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_famfashion.ninas')),
                ('id_producto_ninos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_famfashion.ninos')),
            ],
        ),
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id_reseña', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.PositiveSmallIntegerField()),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('foto_producto', models.ImageField(blank=True, null=True, upload_to='reseñas/')),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reseñas', to='app_famfashion.cliente')),
                ('id_producto_hombre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_famfashion.hombre')),
                ('id_producto_mujer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_famfashion.mujer')),
                ('id_producto_ninas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_famfashion.ninas')),
                ('id_producto_ninos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_famfashion.ninos')),
            ],
        ),
    ]
